import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

export default [
  js.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsparser,
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        WebSocket: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        queueMicrotask: 'readonly',
        AbortController: 'readonly',
        FileReader: 'readonly',
        Blob: 'readonly',
        OffscreenCanvas: 'readonly',
        ImageData: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLDivElement: 'readonly',
        MediaSource: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        WheelEvent: 'readonly',
        CompositionEvent: 'readonly',
        ClipboardEvent: 'readonly',
        TouchEvent: 'readonly',
        File: 'readonly',
        BlobPart: 'readonly',
        HTMLInputElement: 'readonly',
        DOMRect: 'readonly',
        VideoDecoder: 'readonly',
        VideoDecoderConfig: 'readonly',
        VideoFrame: 'readonly',
        EncodedVideoChunk: 'readonly',
        AudioContext: 'readonly',
        AudioDecoder: 'readonly',
        GainNode: 'readonly',
        AudioData: 'readonly',
        EncodedAudioChunk: 'readonly',
        CanvasRenderingContext2D: 'readonly',
        DOMException: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        process: 'readonly',
        fetch: 'readonly',
        RequestInit: 'readonly',
        history: 'readonly',
        location: 'readonly',
        React: 'readonly',
        ResizeObserver: 'readonly',
        localStorage: 'readonly',
        __BRIDGE_BUILD_DATE__: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  {
    files: ['**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        URL: 'readonly',
        console: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        Buffer: 'readonly',
      },
    },
  },
  {
    ignores: ['dist/**', 'node_modules/**', 'src/protos/*.proto', 'src/bridge/generated/**'],
  },
];